# PowerShell Deployment Automation Script for Serverless Real-Time Chat
param(
    [string]$Region = "us-east-1",
    [string]$EnvironmentName = "dev",
    [string]$StackName = "serverless-realtime-chat"
)

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "   Serverless Real-Time Chat AWS Deployment Script       " -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# 1. Check AWS CLI
if (-not (Get-Command "aws" -ErrorAction SilentlyContinue)) {
    Write-Host "[ERROR] AWS CLI is not installed or not in PATH." -ForegroundColor Red
    Write-Host "Please install AWS CLI from: https://awscli.amazonaws.com/AWSCLIV2.msi" -ForegroundColor Yellow
    exit 1
}

# 2. Check AWS SAM CLI
if (-not (Get-Command "sam" -ErrorAction SilentlyContinue)) {
    Write-Host "[ERROR] AWS SAM CLI is not installed or not in PATH." -ForegroundColor Red
    Write-Host "Please install SAM CLI from: https://github.com/aws/aws-sam-cli/releases" -ForegroundColor Yellow
    exit 1
}

# 3. Verify AWS Credentials
Write-Host "[INFO] Verifying AWS Identity..." -ForegroundColor Green
$identity = aws sts get-caller-identity --output json 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Unable to authenticate with AWS. Run 'aws configure' first." -ForegroundColor Red
    exit 1
}
Write-Host "Authenticated: $identity" -ForegroundColor Gray

# 4. SAM Build
Write-Host "[INFO] Building SAM template..." -ForegroundColor Green
Set-Location -Path $PSScriptRoot
sam build --template-file template.yaml

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] SAM build failed." -ForegroundColor Red
    exit 1
}

# 5. SAM Deploy
Write-Host "[INFO] Deploying CloudFormation Stack '$StackName' to region '$Region'..." -ForegroundColor Green
sam deploy `
    --stack-name $StackName `
    --region $Region `
    --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND `
    --resolve-s3 `
    --parameter-overrides EnvironmentName=$EnvironmentName `
    --no-fail-on-empty-changeset

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] SAM deploy failed." -ForegroundColor Red
    exit 1
}

# 6. Extract Outputs and Update Frontend .env
Write-Host "[INFO] Extracting CloudFormation stack outputs..." -ForegroundColor Green
$outputs = aws cloudformation describe-stacks `
    --stack-name $StackName `
    --region $Region `
    --query "Stacks[0].Outputs" `
    --output json | ConvertFrom-Json

$userPoolId = ($outputs | Where-Object { $_.OutputKey -eq "CognitoUserPoolId" }).OutputValue
$clientId = ($outputs | Where-Object { $_.OutputKey -eq "CognitoClientId" }).OutputValue
$wsUrl = ($outputs | Where-Object { $_.OutputKey -eq "WebSocketApiUrl" }).OutputValue
$restUrl = ($outputs | Where-Object { $_.OutputKey -eq "RestApiUrl" }).OutputValue
$bucketName = ($outputs | Where-Object { $_.OutputKey -eq "UserAssetsBucketName" }).OutputValue

$envPath = Join-Path (Split-Path $PSScriptRoot -Parent) "frontend\.env"

$envContent = @"
# Auto-generated by deploy.ps1 on $(Get-Date)
VITE_AWS_REGION=$Region
VITE_COGNITO_USER_POOL_ID=$userPoolId
VITE_COGNITO_CLIENT_ID=$clientId
VITE_WS_API_URL=$wsUrl
VITE_REST_API_URL=$restUrl
VITE_S3_BUCKET_NAME=$bucketName
VITE_USE_MOCK=false
"@

Set-Content -Path $envPath -Value $envContent
Write-Host "[SUCCESS] Frontend environment file updated at: $envPath" -ForegroundColor Green
Write-Host "Deployment complete! Next steps:" -ForegroundColor Cyan
Write-Host "  1. cd ../frontend" -ForegroundColor White
Write-Host "  2. npm install" -ForegroundColor White
Write-Host "  3. npm run dev" -ForegroundColor White
